added dropdown component
Juxtify4Spotify/juxtify-client pull request #25
Opened 2024-07-18 01:35 UTC by AbigailSalazar

Hi! I just started learning react but I'm trying to contribute to the project. I made the dropdown component so far. Tell me if you see any problems.

2024-08-22 12:47 UTC, HitBox38 requested changes
Hi,
Overall this looks good I've a few small suggestions to improve the code.

Thanks for your contribution!

2024-08-22 12:47 UTC, HitBox38 commented on src/components/Dropdown/index.tsx
> +        setCollapsed(!collapsed);
small suggestion:
```tsx
setCollapsed((prev) => !prev)
```

Read more here: https://react.dev/reference/react/useState#setstate-parameters

2024-08-22 12:47 UTC, HitBox38 commented on src/components/Dropdown/index.tsx
Make sure your prettier formatter works.

2024-08-22 17:09 UTC, AbigailSalazar commented on src/components/Dropdown/index.tsx
I didn't have it, now it works ok 👍

2024-08-24 21:24 UTC, HitBox38 approved these changes

2024-08-24 21:25 UTC, merged

2024-08-24 21:29 UTC, HitBox38 commented
@AbigailSalazar thanks for your contribution if you're in the discord feel free to tag me for a contributor role.