Added sidebar component
Juxtify4Spotify/juxtify-client pull request #26
Opened 2024-09-17 01:05 UTC by eswaldots

Added sidebar component

Before:
![image](https://github.com/user-attachments/assets/ede77669-997a-42b3-a785-bb308c44c4ea)

After:
![image](https://github.com/user-attachments/assets/41a6b40e-8788-4541-aa62-08fc2de62d17)

2024-09-17 15:58 UTC, HitBox38 requested changes
small change but aside of that good job!

2024-09-17 15:58 UTC, HitBox38 commented on src/components/Sidebar/index.tsx
> +];
Maybe move this to a constants file?

2024-09-17 16:22 UTC, eswaldots commented on src/components/Sidebar/index.tsx
> +];
You're right, I made those variables for component debugging purposes, I think it would be a good idea to put them in a constants folder and pass them to the component as a default props value.

2024-09-17 16:29 UTC, eswaldots commented
Now the items is in a separated file for future changes

2024-09-17 18:33 UTC, HitBox38 approved these changes

2024-09-17 18:34 UTC, merged

2025-01-02 06:22 UTC, FujimiyaAmane-kun approved these changes
That should be it. Will be waiting for another development. Nice work though.

2025-01-02 06:22 UTC, FujimiyaAmane-kun commented on src/components/Sidebar/MenuItem/index.tsx
> +    </a>
Okay that should do it.

2025-01-02 06:22 UTC, FujimiyaAmane-kun commented on src/components/Sidebar/consts.tsx
> +];
This is for the Buttons Section, nice work though.