Update Playlist component
Juxtify4Spotify/juxtify-client pull request #30
Opened 2024-10-25 22:58 UTC by AbigailSalazar

Updated components:
I added mobile design and made small changes to
- PlaylistHeader
- SideInfo

![imagen](https://github.com/user-attachments/assets/ab8b696c-c815-4e95-91f3-99aed931af3a)

New components added:
- PlaylistItem
![imagen](https://github.com/user-attachments/assets/8f7ea31d-1c37-43c0-816c-d041aa4d83d0)
![imagen](https://github.com/user-attachments/assets/bb904500-03fc-4afc-9f01-dfbdacaad1f8)

- SongList
![imagen](https://github.com/user-attachments/assets/06b4f873-23a6-4b95-a19b-c7b355202c40)

This is how the Playlist component looks complete

- Desktop:
![imagen](https://github.com/user-attachments/assets/b214e544-5339-4288-a66f-103a40d50c4c)

- Moblie:
![imagen](https://github.com/user-attachments/assets/c8b1b018-d12e-4d92-8337-f20d40749f8b)
(To test mobile desing I removed nav and aside menu in browser dev tools)

2024-10-26 20:06 UTC, BostonRohan commented on src/routes/playlist.tsx
> +      {isSmallScreen ? (
Can't we do this via css with the tailwind `sm:` breakpoint, it might be more performant than using javascript

2024-10-26 20:08 UTC, BostonRohan requested changes

2024-10-26 20:08 UTC, BostonRohan commented on src/routes/playlist.tsx
> +      {isSmallScreen ? (
Can we do this using CSS with the tailwind `sm:` breakpoint? It might be more performant than javascript having to calculate the window width.

2024-10-26 22:48 UTC, AbigailSalazar commented on src/routes/playlist.tsx
> +      {isSmallScreen ? (
Yes, we can. I was going to use sm:  first with flex reverse to change the order so it can be SideInfo and then PlaylistHeader in mobile, but I've heard it's not very good for accessibility to use flex reverse.  I'm not sure if there is another way of doing this with css. Another idea I had (using sm:) was to add the playlist image in the header and hidde the aside completely but that would mean repeat a little of code. What would be the best option?

2024-12-20 03:26 UTC, AbigailSalazar commented
I changed to use only tailwind, using flex reverse.

2024-12-20 21:38 UTC, BostonRohan approved these changes

2024-12-20 21:38 UTC, merged

2024-12-20 21:54 UTC, AbigailSalazar commented on src/routes/playlist.tsx
> +      {isSmallScreen ? (
Oh, I didn't saw this message, but it can be easily change if we need in the future.

2024-12-31 12:56 UTC, FujimiyaAmane-kun commented on src/routes/playlist.tsx
> +      {isSmallScreen ? (
And adding some bug testing of this....

2025-01-01 04:33 UTC, FujimiyaAmane-kun approved these changes